name: Deploy DEV and DLY

on:
  push:
    branches:
      - develop

jobs:
  deployDev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cicd-tutorial-pipeline-dev"
          heroku_email: "igordalepiane@gmail.com"
          usedocker: true
  deployDly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cicd-tutorial-pipeline-dly"
          heroku_email: "igordalepiane@gmail.com"
          usedocker: true
